version: "3"
services:
  db:
    image: "postgres"
    restart: always
    container_name: "db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=book-store
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    image: vladimir028/devops-project:latest
    container_name: "app"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book-store"
volumes:
  postgres-data:
