apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-project
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/book-store
  SPRING_DATASOURCE_USERNAME: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops-project
data:
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: devops-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        namespace: devops-project
    spec:
      containers:
        - name: app
          image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: devops-project
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080